import Head from "next/head"
import { Inter } from "@next/font/google"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const handleLogin = () => {
    fetch(`${process.env.NEXT_PUBLIC_BASE_BACK_URL}/login`, {
      method: "POST",
      credentials: "include",
      headers: new Headers({
        "Content-Type": "application/json",
      }),
      body: JSON.stringify({
        email: "mgesualdo14@gmail.com",
        password: "1234",
      }),
    })
  }
  const handleReq = () => {
    fetch(`${process.env.NEXT_PUBLIC_BASE_BACK_URL}`, {
      credentials: "include",
    })
  }

  return (
    <>
      <Head>
        <title>Change Your Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={handleLogin}>LOGIN</button>
        <button onClick={handleReq}>REQUEST</button>
      </main>
    </>
  )
}
